// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsimple_system.h for the primary calling header

#ifndef VERILATED_VSIMPLE_SYSTEM___024ROOT_H_
#define VERILATED_VSIMPLE_SYSTEM___024ROOT_H_  // guard

#include "verilated.h"

class Vsimple_system__Syms;

class Vsimple_system___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(ck_i,0,0);
        VL_IN8(rs_n_i,0,0);
        VL_IN8(jtag_TCK,0,0);
        VL_IN8(jtag_TMS,0,0);
        VL_IN8(jtag_TDI,0,0);
        VL_OUT8(jtag_TDO,0,0);
        CData/*0:0*/ simple_system__DOT__rom_ce;
        CData/*0:0*/ simple_system__DOT____Vcellout__console0__rvalid_o;
        CData/*0:0*/ simple_system__DOT____Vcellout__core_top0__ram_we_o;
        CData/*3:0*/ simple_system__DOT____Vcellout__core_top0__ram_sel_o;
        CData/*0:0*/ simple_system__DOT____Vcellout__core_top0__ram_ce_o;
        CData/*0:0*/ simple_system__DOT__u_bus__DOT__host_sel_req;
        CData/*0:0*/ simple_system__DOT__u_bus__DOT__host_sel_resp;
        CData/*1:0*/ simple_system__DOT__u_bus__DOT__device_sel_req;
        CData/*1:0*/ simple_system__DOT__u_bus__DOT__device_sel_resp;
        CData/*0:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_hd2efabf0__0;
        CData/*0:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_h253b5ff2__0;
        CData/*3:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_h36994927__0;
        CData/*0:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_h07643ed6__0;
        CData/*0:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_h659e6344__0;
        CData/*2:0*/ simple_system__DOT__console0__DOT__sim_finish;
        CData/*0:0*/ simple_system__DOT__u_timer__DOT__timer_we;
        CData/*0:0*/ simple_system__DOT__u_timer__DOT__mtimecmp_we;
        CData/*0:0*/ simple_system__DOT__u_timer__DOT__mtimecmph_we;
        CData/*0:0*/ simple_system__DOT__u_timer__DOT__interrupt_q;
        CData/*0:0*/ simple_system__DOT__u_timer__DOT__interrupt_d;
        CData/*0:0*/ simple_system__DOT__u_timer__DOT__error_d;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctl_ie_type_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctl_set_epc_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctl_set_mtval_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctl_set_cause_o;
        CData/*3:0*/ simple_system__DOT__core_top0__DOT__ctl_trap_casue_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctl_mstatus_ie_clear_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctl_mstatus_ie_set_o;
        CData/*5:0*/ simple_system__DOT__core_top0__DOT__ctl_stall_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctl_flush_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__if_branch_slot_end_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id_next_taken_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id_branch_slot_end_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id_rs1_re_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id_rs2_re_o;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__id_rs1_raddr_o;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__id_rs2_raddr_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id_stall_req_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id_rd_we_o;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__id_rd_waddr_o;
        CData/*3:0*/ simple_system__DOT__core_top0__DOT__id_alusel_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_next_taken_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_slot_end_i;
        CData/*3:0*/ simple_system__DOT__core_top0__DOT__ex_alusel_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_rd_we_i;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__ex_rd_addr_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_csr_we_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_div_start_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_div_annul_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_div_signed_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_tag_o;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__ex_rd_addr_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_request_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_taken_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_call_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_ret_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_jmp_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_branch_redirect_o;
    };
    struct {
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem_rd_we_i;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__mem_rd_addr_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem_csr_we_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem_rd_we_o;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__mem_rd_addr_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem_csr_we_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__wb_rd_we_i;
        CData/*4:0*/ simple_system__DOT__core_top0__DOT__wb_rd_addr_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__wb_csr_we_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__wb_instret_incr_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__div_ready_o;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT____Vcellinp__bp0__stall_i;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__bht_predict_taken_w;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_matched_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_call_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_ret_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_jmp_r;
        CData/*5:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_rd_entry_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__ras_call_matched_w;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__ras_ret_matched_w;
        CData/*5:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_write_entry_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_hit_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_alloc_req;
        CData/*2:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__ras_proven_cur_index_r;
        CData/*2:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__ras_proven_next_index_r;
        CData/*2:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__ras_speculative_cur_index_r;
        CData/*2:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__ras_speculative_next_index_r;
        CData/*5:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__u_lru__DOT__lfsr_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__csr_we;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__ins_valid_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__rs1_load_depend;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__rs2_load_depend;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__pre_ins_is_load;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__excepttype_mret;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__excepttype_ecall;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__excepttype_ebreak;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__excepttype_illegal_inst;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__stall_req_for_div;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__rs1_eq_rs2_w;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__rs1_ge_rs2_signed_w;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__rs1_ge_rs2_unsigned_w;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__read_csr_enable;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT____VdfgExtracted_h8d65eadd__0;
        CData/*5:0*/ simple_system__DOT__core_top0__DOT__div0__DOT__cnt_r;
        CData/*1:0*/ simple_system__DOT__core_top0__DOT__div0__DOT__state_r;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ex_mem0__DOT__branch_tag;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem0__DOT__mem_we;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem0__DOT__mem_re;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem0__DOT__load_operation;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem0__DOT__store_operation;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem0__DOT__load_addr_align_exception;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__mem0__DOT__store_addr_align_exception;
        CData/*3:0*/ simple_system__DOT__core_top0__DOT__ctrl0__DOT__curr_state;
        CData/*3:0*/ simple_system__DOT__core_top0__DOT__ctrl0__DOT__next_state;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctrl0__DOT__eip;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctrl0__DOT__tip;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__ctrl0__DOT__sip;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mstatus_pie;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mstatus_ie;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mie_external;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mie_timer;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mie_sw;
        CData/*3:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__cause;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__int_or_exc;
    };
    struct {
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mip_external;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mip_timer;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mip_sw;
        CData/*0:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__MISALIGNED_EXCEPTION;
        CData/*6:0*/ __VdfgTmp_hb6145d33__0;
        CData/*0:0*/ __Vdpi_export_trigger;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__n_rst_i__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ simple_system__DOT__core_top0__DOT__id_uopcode_o;
        SData/*15:0*/ simple_system__DOT__core_top0__DOT__ex_uop_i;
        SData/*15:0*/ simple_system__DOT__core_top0__DOT__mem_uop_i;
        IData/*31:0*/ simple_system__DOT____Vcellout__core_top0__ram_data_o;
        IData/*31:0*/ simple_system__DOT____Vcellout__core_top0__ram_addr_o;
        IData/*31:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_h75688df5__0;
        IData/*31:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_h753a4492__0;
        IData/*31:0*/ simple_system__DOT__u_bus__DOT____Vlvbound_h4dcf629a__0;
        IData/*31:0*/ simple_system__DOT__console0__DOT__log_fd;
        IData/*31:0*/ simple_system__DOT__u_timer__DOT__rdata_d;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ctl_mtval_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ctl_new_pc_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__if_pc_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id_pc_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id_inst_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id_next_pc_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id_inst_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id_rs1_data_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id_rs2_data_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_pc_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_inst_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_next_pc_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_rs1_data_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_rs2_data_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_imm_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_csr_addr_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_excepttype_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_dividend_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_divisor_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_csr_raddr_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_csr_waddr_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_csr_wdata_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_rd_wdata_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_mem_addr_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_mem_wdata_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_branch_target_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_branch_redirect_pc_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_rd_wd_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_mem_addr_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_mem_wdata_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_csr_waddr_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_csr_wdata_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_excepttype_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_pc_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_inst_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_rd_wdata_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_csr_waddr_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_csr_wdata_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_excepttype_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_pc_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__mem_inst_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__wb_rd_wdata_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__wb_csr_waddr_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__wb_csr_wdata_i;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr_rdata_o;
    };
    struct {
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr_mstatus_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr_mie_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr_mip_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr_mepc_o;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__bims;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__btb_target_pc_r;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__i1;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__update;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__bp0__DOT__i3;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__imm_r;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__id0__DOT__csr_addr;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__pc_add_imm_w;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__rs1_add_imm_w;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__csr_result_r;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__div_result_r;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__jump_result_r;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__logic_result_r;
        VlWide<3>/*64:0*/ simple_system__DOT__core_top0__DOT__div0__DOT__dividend_r;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__div0__DOT__divisor_r;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__ex_mem0__DOT__branch_pc;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mtvec;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mscratch;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mepc;
        IData/*26:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__cause_rem;
        IData/*31:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mtval;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ simple_system__DOT__u_timer__DOT__mtime_q;
        QData/*63:0*/ simple_system__DOT__u_timer__DOT__mtime_d;
        QData/*63:0*/ simple_system__DOT__u_timer__DOT__mtimecmp_q;
        QData/*63:0*/ simple_system__DOT__u_timer__DOT__mtimecmp_d;
        QData/*63:0*/ simple_system__DOT__core_top0__DOT__div_result_o;
        QData/*63:0*/ simple_system__DOT__core_top0__DOT__ex0__DOT__mul_result_w;
        QData/*32:0*/ simple_system__DOT__core_top0__DOT__div0__DOT__div_var_w;
        QData/*63:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__mcycle;
        QData/*63:0*/ simple_system__DOT__core_top0__DOT__csr0__DOT__minstret;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT__host_req;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT__host_gnt;
        VlUnpacked<IData/*31:0*/, 1> simple_system__DOT__host_addr;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT__host_we;
        VlUnpacked<CData/*3:0*/, 1> simple_system__DOT__host_be;
        VlUnpacked<IData/*31:0*/, 1> simple_system__DOT__host_wdata;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT__host_rvalid;
        VlUnpacked<IData/*31:0*/, 1> simple_system__DOT__host_rdata;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT__host_err;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT__device_req;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT__device_addr;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT__device_we;
        VlUnpacked<CData/*3:0*/, 3> simple_system__DOT__device_be;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT__device_wdata;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT__device_rvalid;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT__device_rdata;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT__device_err;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT__cfg_device_addr_base;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT__cfg_device_addr_mask;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT____Vcellinp__u_bus__cfg_device_addr_mask;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT____Vcellinp__u_bus__cfg_device_addr_base;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT____Vcellinp__u_bus__device_err_i;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT____Vcellinp__u_bus__device_rdata_i;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT____Vcellinp__u_bus__device_rvalid_i;
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT____Vcellout__u_bus__device_wdata_o;
        VlUnpacked<CData/*3:0*/, 3> simple_system__DOT____Vcellout__u_bus__device_be_o;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT____Vcellout__u_bus__device_we_o;
    };
    struct {
        VlUnpacked<IData/*31:0*/, 3> simple_system__DOT____Vcellout__u_bus__device_addr_o;
        VlUnpacked<CData/*0:0*/, 3> simple_system__DOT____Vcellout__u_bus__device_req_o;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT____Vcellout__u_bus__host_err_o;
        VlUnpacked<IData/*31:0*/, 1> simple_system__DOT____Vcellout__u_bus__host_rdata_o;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT____Vcellout__u_bus__host_rvalid_o;
        VlUnpacked<IData/*31:0*/, 1> simple_system__DOT____Vcellinp__u_bus__host_wdata_i;
        VlUnpacked<CData/*3:0*/, 1> simple_system__DOT____Vcellinp__u_bus__host_be_i;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT____Vcellinp__u_bus__host_we_i;
        VlUnpacked<IData/*31:0*/, 1> simple_system__DOT____Vcellinp__u_bus__host_addr_i;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT____Vcellout__u_bus__host_gnt_o;
        VlUnpacked<CData/*0:0*/, 1> simple_system__DOT____Vcellinp__u_bus__host_req_i;
        VlUnpacked<IData/*31:0*/, 1048576> simple_system__DOT__data_ram0__DOT__mem;
        VlUnpacked<CData/*1:0*/, 64> simple_system__DOT__core_top0__DOT__bp0__DOT__bht_bim_list_r;
        VlUnpacked<CData/*0:0*/, 64> simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_valid_list_r;
        VlUnpacked<CData/*0:0*/, 64> simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_call_list_r;
        VlUnpacked<CData/*0:0*/, 64> simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_ret_list_r;
        VlUnpacked<CData/*0:0*/, 64> simple_system__DOT__core_top0__DOT__bp0__DOT__btb_is_jmp_list_r;
        VlUnpacked<IData/*31:0*/, 64> simple_system__DOT__core_top0__DOT__bp0__DOT__btb_source_pc_list_r;
        VlUnpacked<IData/*31:0*/, 64> simple_system__DOT__core_top0__DOT__bp0__DOT__btb_target_pc_list_r;
        VlUnpacked<IData/*31:0*/, 8> simple_system__DOT__core_top0__DOT__bp0__DOT__ras_list_r;
        VlUnpacked<IData/*31:0*/, 32> simple_system__DOT__core_top0__DOT__regfile_ins__DOT__regs;
        VlUnpacked<CData/*0:0*/, 9> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VicoTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vsimple_system__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsimple_system___024root(Vsimple_system__Syms* symsp, const char* v__name);
    ~Vsimple_system___024root();
    VL_UNCOPYABLE(Vsimple_system___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
